// Lote 3 de aprofundamento: temas ainda descobertos do mapa (conteudo/temas-mercado.md).
// Conteúdo sujeito a validação da advogada responsável.

/* ===== PREVIDENCIÁRIO ===== */
const GRACA_FU = {
  title: "Vamos calcular até quando você mantém a qualidade de segurado?",
  intro: "3 perguntas. Mostramos a data-limite estimada.",
  questions: [
    { id: "ultima", q: "Qual foi o mês da sua última contribuição (ou da saída do último emprego)?", input: "date" },
    { id: "mais120", q: "Você já tem mais de 120 contribuições sem ter perdido a qualidade de segurado no meio?", a: ["Sim", "Não", "Não sei"] },
    { id: "desemprego", q: "Ficou desempregado(a) e pode comprovar (seguro-desemprego ou registro no SINE)?", a: ["Sim", "Não", "Eu contribuía como autônomo/facultativo"] },
  ],
  evaluate(a) {
    let meses = a.desemprego === "Eu contribuía como autônomo/facultativo" ? 12 : 12;
    const items = [];
    if (a.mais120 === "Sim") { meses += 12; items.push("Mais de 120 contribuições sem perder a qualidade: +12 meses."); }
    if (a.desemprego === "Sim") { meses += 12; items.push("Desemprego comprovado: +12 meses."); }
    if (a.desemprego === "Eu contribuía como autônomo/facultativo") items.push("Atenção: para o segurado facultativo, o período de graça é de apenas 6 meses. O cálculo abaixo considera contribuinte individual (12 meses).");
    if (!a.ultima) return { headline: `Seu período de graça é de cerca de ${meses} meses após a última contribuição.`, tone: "info", items, lawyer: false, summary: `Período de graça: ${meses} meses.` };
    const fim = new Date(a.ultima); fim.setMonth(fim.getMonth() + meses + 1); fim.setDate(16);
    const left = daysLeft(fim);
    items.push("A qualidade de segurado se mantém até o dia 15 do segundo mês seguinte ao fim do período de graça. Enquanto isso, você mantém direito a benefícios como auxílio por incapacidade e, para seus dependentes, pensão.");
    items.push("Para não perder, basta voltar a contribuir antes da data-limite, nem que seja como facultativo.");
    return { headline: left >= 0 ? `Você mantém a qualidade de segurado até cerca de ${fim.toLocaleDateString("pt-BR")} (${left} dias).` : `Pela estimativa, a qualidade de segurado foi perdida em ${fim.toLocaleDateString("pt-BR")}.`,
      tone: left >= 60 ? "good" : left >= 0 ? "near" : "info", items, lawyer: left < 0,
      summary: `Período de graça: última contribuição ${a.ultima.toLocaleDateString("pt-BR")}; ${meses} meses; limite ${fim.toLocaleDateString("pt-BR")}.` };
  },
};

FAQ.push(
  { id: "periodo-graca", area: "previdenciario", all: [["qualidade de segurado", "período de graça", "periodo de graca", "parei de contribuir", "parei de pagar", "sem contribuir", "desempregad"]],
    q: "Parei de contribuir. Até quando continuo segurado(a) do INSS?",
    a: ["Depois da última contribuição, você continua segurado(a) por um período chamado período de graça: em regra 12 meses (6 meses para o facultativo).",
      "Esse prazo aumenta mais 12 meses para quem tem mais de 120 contribuições sem ter perdido a qualidade de segurado, e mais 12 meses para quem comprova desemprego. Pode chegar a 36 meses.",
      "Durante o período de graça, você mantém direito aos benefícios, e seus dependentes mantêm direito à pensão por morte."],
    sources: [["Lei 8.213/1991, art. 15", P + "leis/l8213cons.htm"]], next: "Vamos calcular a sua data-limite?", followUp: GRACA_FU },
  { id: "auxilio-acidente", area: "previdenciario", all: [["auxílio-acidente", "auxilio-acidente", "auxilio acidente", "auxílio acidente", "sequela"]],
    q: "Quem tem direito ao auxílio-acidente?",
    a: ["É uma indenização mensal para quem ficou com sequela permanente que reduz a capacidade para o trabalho que exercia, depois de um acidente de qualquer natureza (não precisa ser do trabalho).",
      "Vale 50% do salário de benefício, é pago junto com o salário e dura até a aposentadoria. Não exige carência.",
      "Têm direito: empregado, empregado doméstico, trabalhador avulso e segurado especial. Contribuinte individual e facultativo não têm direito.",
      "Muitas pessoas têm direito e não sabem: o pedido pode ser feito mesmo anos depois, desde que a sequela seja comprovada."],
    sources: [["Lei 8.213/1991, art. 86", P + "leis/l8213cons.htm"]], next: "Quer verificar se sua sequela dá direito?" },
  { id: "rural", area: "previdenciario", all: [["rural", "roça", "roca", "lavoura", "agricult", "pescador", "segurado especial", "trabalhei no campo"]],
    q: "Como funciona a aposentadoria rural e a híbrida?",
    a: ["A aposentadoria rural por idade exige 60 anos (homem) ou 55 anos (mulher) e 15 anos de atividade rural, mesmo sem contribuições, para o segurado especial (agricultor familiar, pescador artesanal).",
      "A atividade rural é provada com início de prova material (notas de produtor, ITR, certidões com profissão de lavrador, documentos de sindicato) e testemunhas. A autodeclaração validada pelo INSS também é usada.",
      "A aposentadoria híbrida soma tempo rural e urbano. Segue a idade da regra urbana e permite contar tempo rural antigo, mesmo anterior a 1991 (STJ, Tema 1.007)."],
    sources: [["Lei 8.213/1991, arts. 11, VII, 39, 48 e 106", P + "leis/l8213cons.htm"], ["STJ — Tema 1.007", "https://processo.stj.jus.br/repetitivos/temas_repetitivos/"]], next: "Quer avaliar seu tempo rural?" },
  { id: "conversao-especial", area: "previdenciario", all: [["convers", "converter"], ["especial", "insalubr"]],
    q: "Posso converter tempo especial em tempo comum?",
    a: ["Sim, mas só para períodos trabalhados até 13/11/2019, data da Reforma. Depois disso, a conversão foi proibida.",
      "Para quem precisaria de 25 anos de atividade especial, o tempo é multiplicado por 1,4 (homem) ou 1,2 (mulher). Cada 10 anos especiais viram 14 (homem) ou 12 (mulher).",
      "O acréscimo pode antecipar a aposentadoria ou aumentar o valor. É preciso comprovar a exposição com PPP e, conforme a época, LTCAT."],
    sources: [["Lei 8.213/1991, art. 57, §5º", P + "leis/l8213cons.htm"], ["EC 103/2019, art. 25, §2º", P + "constituicao/emendas/emc/emc103.htm"]], next: "Quer calcular o acréscimo no seu tempo?" },
  { id: "auxilio-reclusao", area: "previdenciario", all: [["reclusão", "reclusao", "preso", "presídio", "presidio", "prisão", "prisao"]],
    q: "Como funciona o auxílio-reclusão?",
    a: ["É pago aos dependentes do segurado de baixa renda preso em regime fechado. O limite de baixa renda é fixado anualmente pelo governo.",
      "Exige 24 contribuições do segurado (carência) e que ele tivesse qualidade de segurado na data da prisão.",
      "O valor é de um salário mínimo. O benefício deixa de ser pago se o preso fugir, progredir para o semiaberto ou for solto. É preciso apresentar a cada 3 meses a certidão de recolhimento prisional."],
    sources: [["Lei 8.213/1991, art. 80", P + "leis/l8213cons.htm"], ["EC 103/2019, art. 27", P + "constituicao/emendas/emc/emc103.htm"]], next: "Quer verificar o direito da sua família?" },
  { id: "vida-toda", area: "previdenciario", all: [["vida toda"]],
    q: "Ainda dá para pedir a revisão da vida toda?",
    a: ["Não. Em 2024, o STF decidiu que a regra de transição da Lei 9.876/1999 é obrigatória, o que na prática encerrou a revisão da vida toda.",
      "Quem tinha ação em andamento deve acompanhar a decisão sobre os efeitos no seu processo, inclusive quanto à devolução de valores.",
      "Outras revisões continuam possíveis: tempo não computado, atividade especial, salários errados no cálculo. Vale analisar sua carta de concessão."],
    sources: [["STF — ADIs 2.110 e 2.111", "https://portal.stf.jus.br"]], next: "Quer verificar outras revisões no seu benefício?" },
  { id: "adicional-25", area: "previdenciario", all: [["25%", "25 por cento", "acréscimo", "acrescimo", "grande invalidez", "cuidador"]],
    q: "Quem tem direito ao acréscimo de 25% na aposentadoria?",
    a: ["O aposentado por incapacidade permanente (antiga invalidez) que precisa de ajuda permanente de outra pessoa para as atividades do dia a dia.",
      "O acréscimo vale mesmo que ultrapasse o teto do INSS e acaba com a morte do aposentado (não passa para a pensão).",
      "O STF decidiu que o acréscimo não pode ser estendido a outros tipos de aposentadoria (Tema 1.095)."],
    sources: [["Lei 8.213/1991, art. 45", P + "leis/l8213cons.htm"], ["STF — Tema 1.095", "https://portal.stf.jus.br/jurisprudenciaRepercussao/"]], next: "Quer pedir o acréscimo?" },
  { id: "complementacao", area: "previdenciario", all: [["complement", "abaixo do mínimo", "abaixo do minimo", "mei", "5%", "11%", "plano simplificado", "contribuição em atraso", "contribuicao em atraso", "pagar atrasado"]],
    q: "Contribuo como MEI ou pelo plano simplificado. Isso conta para aposentadoria?",
    a: ["As contribuições de 5% (MEI e facultativo de baixa renda) e de 11% (plano simplificado) contam para a aposentadoria por idade e para os demais benefícios, mas não para aposentadorias que exigem tempo de contribuição, como a regra dos pontos.",
      "Para usar esse tempo em outras regras, é possível complementar a contribuição até 20%, com juros e multa.",
      "Depois da Reforma, meses com contribuição abaixo do salário mínimo só contam se forem complementados, agrupados com outros meses ou compensados com o excedente de outros meses.",
      "Contribuições em atraso de autônomo podem ser pagas, mas não valem para carência quando anteriores à primeira contribuição em dia."],
    sources: [["Lei 8.212/1991, art. 21", P + "leis/l8212cons.htm"], ["EC 103/2019, art. 29", P + "constituicao/emendas/emc/emc103.htm"]], next: "Quer saber se vale a pena complementar?" },
  { id: "tempo-militar", area: "previdenciario", all: [["serviço militar", "servico militar", "exército", "exercito", "quartel", "aluno-aprendiz", "aluno aprendiz", "averba"]],
    q: "Tempo de serviço militar e de aluno-aprendiz contam para aposentadoria?",
    a: ["O serviço militar obrigatório conta como tempo de contribuição. Basta apresentar a certidão de tempo de serviço militar emitida pelas Forças Armadas.",
      "O tempo de aluno-aprendiz em escola técnica pública pode ser contado se houve remuneração, mesmo indireta (alimentação, fardamento, material), à conta do orçamento público. [VALIDAR critérios atuais]",
      "Esses períodos costumam não aparecer no CNIS: é preciso pedir a averbação ao INSS com os documentos."],
    sources: [["Lei 8.213/1991, art. 55", P + "leis/l8213cons.htm"]], next: "Quer incluir esse tempo na sua contagem?" },
);

/* ===== SAÚDE ===== */
FAQ.push(
  { id: "opme-protese", prio: 2, area: "saude", all: [["prótese", "protese", "órtese", "ortese", "opme", "material cirúrgico", "material cirurgico", "stent", "parafuso", "placa"]],
    q: "O plano pode negar a prótese ou o material da cirurgia?",
    a: ["Próteses, órteses e materiais ligados ao ato cirúrgico (OPME) são de cobertura obrigatória quando a cirurgia é coberta.",
      "O médico define as características técnicas do material, mas não pode exigir marca. Se houver divergência, a operadora deve instaurar junta médica, com participação do seu médico, em prazo definido pela ANS.",
      "Próteses e órteses que não têm ligação com cirurgia (como óculos ou cadeira de rodas) em regra não são obrigatórias."],
    sources: [["Lei 9.656/1998, art. 10, VII", P + "leis/l9656.htm"], ["ANS — junta médica (RN 424/2017)", "https://www.gov.br/ans"]], next: "O plano negou o material?", followUp: SAUDE_NEGATIVA_FU },
  { id: "fertilizacao", area: "saude", all: [["fertiliza", "fiv", "reprodução assistida", "reproducao assistida", "inseminação", "inseminacao", "infertilidade", "congelamento de óvulos"]],
    q: "O plano é obrigado a cobrir fertilização in vitro?",
    a: ["Em regra, não. O STJ decidiu que os planos não são obrigados a custear fertilização in vitro, salvo se o contrato prever (Tema 1.067).",
      "Outros tratamentos ligados à infertilidade, como cirurgias e exames de diagnóstico, seguem o rol da ANS.",
      "Há discussão específica para congelamento de óvulos de pacientes com câncer antes da quimioterapia, em que algumas decisões determinam a cobertura."],
    sources: [["Lei 9.656/1998, art. 10, III", P + "leis/l9656.htm"], ["STJ — Tema 1.067", "https://processo.stj.jus.br/repetitivos/temas_repetitivos/"]], next: "Quer avaliar seu caso?" },
  { id: "portabilidade", area: "saude", all: [["portabilidade", "trocar de plano", "mudar de plano"]],
    q: "Como trocar de plano sem cumprir nova carência?",
    a: ["Pela portabilidade de carências, você muda de plano levando as carências já cumpridas.",
      "Requisitos principais: plano atual ativo e em dia; permanência mínima de 2 anos no plano de origem na primeira portabilidade (3 anos se cumpriu cobertura parcial temporária) e de 1 ano nas seguintes; plano de destino em faixa de preço compatível.",
      "Use o Guia ANS de Planos de Saúde para encontrar planos compatíveis. Quem foi demitido(a) ou teve o plano cancelado tem regras especiais, sem prazo mínimo."],
    sources: [["ANS — portabilidade de carências", "https://www.gov.br/ans/pt-br/assuntos/consumidor/portabilidade-de-carencias"]], next: "Quer ajuda para fazer a portabilidade?" },
  { id: "uti-sus", area: "saude", all: [["uti", "leito", "vaga", "regulação", "regulacao", "transferência", "transferencia"], ["sus", "hospital", "internação", "internacao", "upa"]],
    q: "Não há vaga de UTI ou leito pelo SUS. O que fazer?",
    a: ["O paciente deve estar inscrito na central de regulação. Peça ao hospital o número da solicitação e o relatório médico com a indicação de UTI.",
      "Sem vaga em tempo adequado, cabe ação urgente contra o município ou o estado. A Justiça pode determinar a transferência ou a internação em hospital particular às custas do poder público.",
      "A Defensoria Pública atua nesses casos com urgência e gratuitamente. O plantão judiciário funciona fora do horário comercial."],
    sources: [["Constituição Federal, art. 196", P + "constituicao/constituicao.htm"], ["Lei 8.080/1990", P + "leis/l8080.htm"]], next: "É urgente agora?" },
  { id: "odontologico", area: "saude", all: [["dentista", "odontol", "implante", "aparelho ortodôntico", "canal", "plano dental"]],
    q: "Quais meus direitos em problemas com dentista ou plano odontológico?",
    a: ["O plano odontológico deve cobrir os procedimentos do rol da ANS para a segmentação odontológica, como consultas, restaurações, tratamento de canal, extrações e algumas cirurgias.",
      "Implantes e aparelhos ortodônticos em regra não são obrigatórios, salvo se o contrato prever.",
      "Em erro de dentista, o profissional responde se houver culpa. Em tratamentos estéticos com resultado prometido, a responsabilidade costuma ser mais rigorosa. Guarde o prontuário, as radiografias e o orçamento."],
    sources: [["Lei 9.656/1998", P + "leis/l9656.htm"], ["CDC, art. 14, §4º", P + "leis/l8078compilado.htm"]], next: "Quer avaliar seu caso?" },
);

/* ===== CONSUMIDOR E BANCÁRIO ===== */
FAQ.push(
  { id: "juros-abusivos", area: "consumidor", all: [["juros", "financiamento", "revisional", "revisão de contrato", "revisao de contrato", "parcela alta"]],
    q: "Os juros do meu financiamento ou empréstimo são abusivos?",
    a: ["Juros acima de 12% ao ano não são abusivos por si só (STJ, Súmula 382). A abusividade aparece quando a taxa fica muito acima da média de mercado para aquela operação, divulgada pelo Banco Central.",
      "Também podem ser questionados: tarifas e seguros embutidos sem escolha (venda casada), capitalização de juros não prevista de forma clara e encargos de atraso acumulados.",
      "Antes de qualquer medida, compare a taxa do seu contrato com a média do Banco Central na data da contratação. Continuar pagando evita a negativação enquanto se discute."],
    sources: [["STJ — Súmulas 382 e 539", "https://scon.stj.jus.br/SCON/sumstj/"], ["Banco Central — taxas médias de juros", "https://www.bcb.gov.br/estatisticas/txjuros"]], next: "Quer comparar seu contrato com a média?" },
  { id: "compra-nao-reconhecida", area: "consumidor", all: [["cartão", "cartao", "fatura"], ["não reconheço", "nao reconheco", "não fiz", "nao fiz", "clonad", "compra estranha", "fraude"]],
    q: "Apareceram compras no cartão que eu não fiz. O que fazer?",
    a: ["Bloqueie o cartão e conteste as compras imediatamente com o banco, pelo aplicativo ou pela central, e anote o protocolo.",
      "O banco responde por fraudes de terceiros ligadas ao seu serviço (STJ, Súmula 479). Cabe a ele provar que a compra foi sua.",
      "Se o banco negar o estorno, registre reclamação no Banco Central e no consumidor.gov.br. Cobranças mantidas indevidamente podem gerar devolução e indenização."],
    sources: [["STJ — Súmula 479", "https://scon.stj.jus.br/SCON/sumstj/"], ["Banco Central — reclamações", "https://www.bcb.gov.br/meubc/registrar_reclamacao"]], next: "O banco negou o estorno?" },
  { id: "conta-invadida", area: "consumidor", all: [["invadi", "hacke", "clonaram", "roubaram meu celular", "furtaram meu celular", "whatsapp clonado", "aplicativo do banco"]],
    q: "Meu celular foi roubado ou minha conta foi invadida. O que fazer?",
    a: ["Ligue para o banco e bloqueie contas, cartões e aplicativos. Peça à operadora o bloqueio do chip e registre boletim de ocorrência.",
      "Avise seus contatos se o WhatsApp foi clonado e recupere a conta pelo próprio aplicativo, ativando a verificação em duas etapas.",
      "Se houve transferências ou empréstimos feitos pelos criminosos fora do seu perfil habitual, o banco pode ser responsabilizado por falha de segurança. Peça o MED (Pix) e conteste as operações."],
    sources: [["STJ — Súmula 479", "https://scon.stj.jus.br/SCON/sumstj/"], ["Banco Central — MED", "https://www.bcb.gov.br/estabilidadefinanceira/pix"]], next: "Houve prejuízo financeiro?" },
  { id: "tarifas-venda-casada", area: "consumidor", all: [["tarifa", "pacote de serviços", "venda casada", "seguro embutido", "seguro prestamista", "título de capitalização"]],
    q: "O banco cobrou tarifa ou seguro que eu não pedi. Posso reaver?",
    a: ["Existe um conjunto de serviços bancários essenciais gratuitos, como certas quantidades de saques, extratos e transferências. Cobrar por eles é irregular.",
      "Condicionar o empréstimo à contratação de seguro, capitalização ou outro produto é venda casada, proibida pelo CDC. O STJ entende que o consumidor deve poder escolher a seguradora.",
      "Peça o cancelamento e a devolução dos valores. Se pagou indevidamente, a devolução pode ser em dobro."],
    sources: [["CDC, art. 39, I", P + "leis/l8078compilado.htm"], ["Resolução CMN 3.919/2010", "https://www.bcb.gov.br"], ["STJ — Tema 972", "https://processo.stj.jus.br/repetitivos/temas_repetitivos/"]], next: "Quer pedir a devolução?" },
  { id: "academia-curso", area: "consumidor", all: [["academia", "curso", "faculdade", "escola", "mensalidade escolar", "matrícula", "matricula"], ["cancel", "multa", "desist", "trancar"]],
    q: "Quero cancelar academia, curso ou faculdade. Posso ser multado(a)?",
    a: ["Você pode cancelar a qualquer momento. Multa só é válida se estiver no contrato, for proporcional e não for excessiva (em geral, considera-se razoável algo em torno de 10% a 20% do saldo restante).",
      "Curso contratado pela internet pode ser cancelado em até 7 dias com devolução integral.",
      "Na faculdade, a instituição não pode reter documentos (como histórico) por falta de pagamento. Mensalidades já pagas por período não cursado podem ser devolvidas proporcionalmente."],
    sources: [["CDC, arts. 49 e 51", P + "leis/l8078compilado.htm"], ["Lei 9.870/1999", P + "leis/l9870.htm"]], next: "A empresa cobrou multa abusiva?" },
  { id: "turismo", area: "consumidor", all: [["pacote", "agência de viagem", "agencia de viagem", "hotel", "hospedagem", "cruzeiro", "reserva"], ["cancel", "reembolso", "problema", "não", "overbooking"]],
    q: "Tive problema com pacote de viagem ou hospedagem. Quem responde?",
    a: ["A agência de viagens e os fornecedores do pacote (hotel, companhia aérea, operadora) respondem juntos pelos problemas.",
      "Se você cancelar, a retenção deve seguir o contrato e ser proporcional. Se o fornecedor cancelar ou não prestar o serviço, você tem direito a reembolso integral ou a serviço equivalente.",
      "Hotel que não honra a reserva deve providenciar acomodação equivalente e arcar com a diferença. Guarde vouchers, e-mails e comprovantes."],
    sources: [["CDC, arts. 7º, 14 e 25", P + "leis/l8078compilado.htm"]], next: "Quer orientação para o seu caso?" },
  { id: "vazamento-dados", area: "consumidor", all: [["vazamento", "vazaram", "lgpd", "dados pessoais", "meus dados"]],
    q: "Meus dados vazaram. Tenho direito a indenização?",
    a: ["A empresa responsável pelos dados deve comunicar o incidente aos titulares e à ANPD quando houver risco relevante.",
      "Segundo o STJ, o vazamento de dados comuns (nome, telefone, endereço) não gera dano moral automático: é preciso provar o prejuízo. Dados sensíveis ou uso efetivo em fraude mudam a análise.",
      "Você pode pedir à empresa informações sobre quais dados foram vazados e o que ela fez, e reclamar na ANPD."],
    sources: [["Lei 13.709/2018 (LGPD), arts. 42 e 48", P + "_ato2015-2018/2018/lei/l13709.htm"], ["ANPD", "https://www.gov.br/anpd"]], next: "Seus dados foram usados em fraude?" },
);

/* ===== ADMINISTRATIVO ===== */
const LAI_FU = {
  title: "Vamos calcular o prazo de resposta?",
  intro: "Informe a data do pedido.",
  questions: [
    { id: "data", q: "Em que data você fez o pedido de informação?", input: "date" },
    { id: "prorrog", q: "O órgão avisou que prorrogou o prazo?", a: ["Sim", "Não"] },
  ],
  evaluate(a) {
    if (!a.data) return { headline: "O órgão tem 20 dias para responder, prorrogáveis por mais 10.", tone: "info", items: [], lawyer: false, summary: "LAI: data não informada." };
    const d = deadlineText(addDays(a.data, a.prorrog === "Sim" ? 30 : 20));
    return { headline: `Prazo de resposta: ${d.text}`, tone: d.tone, lawyer: false,
      items: ["Sem resposta no prazo, você pode recorrer à autoridade superior.", "Se a resposta negar o acesso, o recurso deve ser apresentado em 10 dias.", "No governo federal, pedidos e recursos são feitos pela plataforma Fala.BR."],
      summary: `LAI: pedido em ${a.data.toLocaleDateString("pt-BR")}; prorrogado: ${a.prorrog}.` };
  },
};

FAQ.push(
  { id: "direitos-servidor", area: "administrativo", all: [["servidor", "servidora"], ["progressão", "progressao", "promoção", "promocao", "licença", "licenca", "remoção", "remocao", "adicional", "gratificação", "gratificacao", "férias", "ferias"]],
    q: "Quais direitos do servidor público costumam ser negados?",
    a: ["Os mais comuns: progressões e promoções atrasadas, adicionais (insalubridade, noturno, tempo de serviço) não pagos, licenças negadas e pedidos de remoção para acompanhar cônjuge ou por motivo de saúde.",
      "Cada ente (União, estado, município) tem seu estatuto e seu plano de carreira. O primeiro passo é identificar a lei que rege o seu cargo.",
      "Faça o pedido por escrito e guarde o protocolo. Valores atrasados podem ser cobrados dos últimos 5 anos."],
    sources: [["Lei 8.112/1990 (federal)", P + "leis/l8112cons.htm"], ["Decreto 20.910/1932 (prescrição)", P + "decreto/antigos/d20910.htm"]], next: "Qual direito foi negado a você?" },
  { id: "improbidade", area: "administrativo", all: [["improbidade"]],
    q: "Fui acusado(a) de improbidade administrativa. O que mudou na lei?",
    a: ["Desde a Lei 14.230/2021, só há improbidade com dolo: a vontade livre e consciente de praticar o ato ilícito. Erro, mesmo grosseiro, não configura improbidade.",
      "Só o Ministério Público pode propor a ação. A prescrição é de 8 anos, com marcos de interrupção.",
      "As sanções incluem perda da função, suspensão dos direitos políticos, multa e proibição de contratar com o poder público, aplicadas de forma proporcional. O ressarcimento ao erário é tratado à parte."],
    sources: [["Lei 8.429/1992 (com a Lei 14.230/2021)", P + "leis/l8429.htm"]], next: "Quer ajuda com a defesa?" },
  { id: "responsabilidade-estado", area: "administrativo", all: [["indeniza", "prejuízo", "prejuizo", "dano", "acidente", "buraco"], ["prefeitura", "estado", "governo", "órgão público", "orgao publico", "poder público", "viatura", "hospital público", "escola pública"]],
    q: "O poder público causou um prejuízo. Posso pedir indenização?",
    a: ["Sim. O Estado responde pelos danos causados por seus agentes independentemente de culpa: basta provar o dano e a relação com a atuação (ou omissão relevante) do poder público.",
      "Exemplos comuns: acidentes por buracos na via, erros em hospital público, danos causados por viaturas, prisões indevidas.",
      "O prazo para pedir indenização contra o poder público é de 5 anos."],
    sources: [["Constituição Federal, art. 37, §6º", P + "constituicao/constituicao.htm"], ["Decreto 20.910/1932", P + "decreto/antigos/d20910.htm"]], next: "Quer avaliar seu caso?" },
  { id: "desapropriacao", area: "administrativo", all: [["desapropria"]],
    q: "Meu imóvel vai ser desapropriado. Quais meus direitos?",
    a: ["A desapropriação exige indenização prévia, justa e em dinheiro (salvo exceções da reforma agrária e urbana).",
      "Você pode discutir o valor oferecido. Na ação de desapropriação, um perito judicial avalia o imóvel.",
      "Também podem ser devidos juros e indenização por benfeitorias e fundo de comércio. Se o poder público ocupar o imóvel sem processo regular, cabe ação de desapropriação indireta."],
    sources: [["Constituição Federal, art. 5º, XXIV", P + "constituicao/constituicao.htm"], ["Decreto-Lei 3.365/1941", P + "decreto-lei/del3365.htm"]], next: "Quer avaliar a indenização oferecida?" },
  { id: "lai", area: "administrativo", all: [["acesso à informação", "acesso a informacao", "lai", "transparência", "transparencia", "fala.br", "pedido de informação"]],
    q: "Como pedir informações a um órgão público?",
    a: ["Qualquer pessoa pode pedir informações públicas, sem justificar o motivo. O pedido é gratuito.",
      "O órgão tem 20 dias para responder, prorrogáveis por mais 10, com justificativa.",
      "Se o acesso for negado, você pode recorrer em 10 dias. No governo federal, use a plataforma Fala.BR. Estados e municípios têm seus próprios canais."],
    sources: [["Lei 12.527/2011 (LAI)", P + "_ato2011-2014/2011/lei/l12527.htm"]], next: "Seu pedido está sem resposta?", followUp: LAI_FU },
  { id: "auto-infracao", area: "administrativo", all: [["auto de infração", "auto de infracao", "vigilância sanitária", "vigilancia sanitaria", "interdição", "interdicao", "alvará", "alvara", "fiscalização", "fiscalizacao", "multa do procon", "ibama"]],
    q: "Minha empresa recebeu auto de infração ou teve o alvará negado. O que fazer?",
    a: ["Leia a notificação: ela informa o prazo de defesa, que costuma ser curto. Apresente a defesa por escrito dentro dele.",
      "O auto deve descrever o fato, a norma violada e a penalidade. Falhas nesses elementos podem anular a autuação.",
      "Cabe recurso contra a decisão. Interdição ou apreensão sem direito de defesa, fora de situação de risco imediato, pode ser questionada na Justiça."],
    sources: [["Lei 9.784/1999 (processo administrativo federal)", P + "leis/l9784.htm"]], next: "Quer ajuda com a defesa?" },
);

/* ===== CARTÓRIO ===== */
FAQ.push(
  { id: "compra-imovel", area: "cartorio", all: [["comprar", "compra", "vender", "venda"], ["imóvel", "imovel", "casa", "apartamento", "terreno", "lote"]],
    q: "O que é preciso para comprar um imóvel com segurança?",
    a: ["Peça a certidão de matrícula atualizada no Registro de Imóveis: ela mostra o dono, dívidas, penhoras e outras restrições.",
      "Peça também certidões do vendedor (ações cíveis, trabalhistas, fiscais e protestos) para evitar fraude contra credores.",
      "Imóvel de valor acima de 30 salários mínimos exige escritura pública. Depois, registre a escritura: só o registro transfere a propriedade. Antes, é preciso pagar o ITBI ao município."],
    sources: [["Código Civil, arts. 108 e 1.245", P + "leis/2002/l10406compilada.htm"], ["Lei 6.015/1973", P + "leis/l6015compilada.htm"]], next: "Quer revisar a documentação da compra?" },
  { id: "reurb", area: "cartorio", all: [["reurb", "regularização fundiária", "regularizacao fundiaria", "loteamento irregular", "favela", "comunidade", "ocupação", "ocupacao"]],
    q: "Moro em área irregular. Como regularizar?",
    a: ["A Regularização Fundiária Urbana (REURB) permite regularizar núcleos urbanos informais e dar título de propriedade aos moradores.",
      "Na REURB Social, voltada a população de baixa renda, os custos de registro são gratuitos. Na REURB Específica, os interessados pagam.",
      "O pedido é feito à prefeitura, por moradores, associações, Defensoria ou Ministério Público."],
    sources: [["Lei 13.465/2017", P + "_ato2015-2018/2017/lei/l13465.htm"]], next: "Quer orientação sobre a REURB?" },
  { id: "socioafetiva", area: "cartorio", all: [["socioafetiv", "padrasto", "madrasta", "criei como filho", "reconhecer filho", "reconhecimento de paternidade", "reconhecimento de maternidade"]],
    q: "Posso reconhecer um filho socioafetivo em cartório?",
    a: ["Sim. O reconhecimento de paternidade ou maternidade socioafetiva pode ser feito direto no Registro Civil para filhos a partir de 12 anos.",
      "É necessário o consentimento do filho (se tiver 12 anos ou mais) e dos pais registrais. O vínculo afetivo deve ser demonstrado.",
      "Para filhos menores de 12 anos, ou se faltar algum consentimento, o caminho é judicial. O reconhecimento gera todos os efeitos de filiação, inclusive herança."],
    sources: [["Provimento CNJ 149/2023 (Código Nacional de Normas)", "https://atos.cnj.jus.br"]], next: "Quer orientação para o reconhecimento?" },
  { id: "regime-bens", area: "cartorio", all: [["regime de bens", "comunhão", "comunhao", "separação de bens", "separacao de bens", "pacto antenupcial"]],
    q: "Posso mudar o regime de bens do casamento?",
    a: ["Sim. A alteração exige pedido do casal, com motivo, e não pode prejudicar terceiros (credores). Tradicionalmente é feita na Justiça. [VALIDAR: possibilidade atual pela via extrajudicial]",
      "Antes do casamento, o regime é escolhido por pacto antenupcial, feito por escritura pública no Tabelionato de Notas. Sem pacto, vale a comunhão parcial.",
      "Pessoas com mais de 70 anos, por lei, casam no regime de separação obrigatória, mas o STF admitiu afastar essa regra por escritura pública (Tema 1.236)."],
    sources: [["Código Civil, arts. 1.639 e 1.641", P + "leis/2002/l10406compilada.htm"], ["STF — Tema 1.236", "https://portal.stf.jus.br/jurisprudenciaRepercussao/"]], next: "Quer orientação sobre o regime de bens?" },
  { id: "apostila", area: "cartorio", all: [["apostila", "haia", "documento para usar no exterior", "cidadania", "tradução juramentada", "traducao juramentada"]],
    q: "Como validar documentos brasileiros para usar no exterior?",
    a: ["Para países que fazem parte da Convenção da Apostila de Haia, basta apostilar o documento em qualquer cartório habilitado. Não é preciso passar pelo consulado.",
      "Certidões de nascimento e casamento para processos de cidadania costumam precisar estar em inteiro teor e atualizadas antes do apostilamento.",
      "Confira se o país de destino exige tradução juramentada, e se a tradução deve ser feita antes ou depois da apostila."],
    sources: [["Resolução CNJ 228/2016", "https://atos.cnj.jus.br"]], next: "Precisa de orientação para o seu processo?" },
  { id: "alvara-valores", area: "cartorio", all: [["fgts", "pis", "saldo", "conta bancária", "conta bancaria", "poupança", "poupanca", "alvará", "alvara"], ["falec", "morreu", "herança", "heranca", "herdeiro"]],
    q: "Como sacar FGTS, PIS ou saldo bancário de quem faleceu?",
    a: ["Valores de FGTS, PIS-Pasep e saldos de salários são pagos aos dependentes habilitados no INSS, sem inventário.",
      "Na falta de dependentes, ou para saldos bancários e restituições de pequeno valor sem outros bens, é possível pedir alvará judicial, um procedimento mais simples que o inventário.",
      "Se houver outros bens, os valores entram no inventário (que pode ser em cartório)."],
    sources: [["Lei 6.858/1980", P + "leis/l6858.htm"]], next: "Quer orientação para liberar os valores?" },
  { id: "inventario-negativo", prio: 2, area: "cartorio", all: [["inventário negativo", "inventario negativo", "não deixou bens", "nao deixou bens"]],
    q: "Preciso fazer inventário se a pessoa não deixou bens?",
    a: ["Não é obrigatório, mas o inventário negativo pode ser útil: ele declara oficialmente que não há bens.",
      "Serve, por exemplo, para o viúvo ou viúva que quer se casar de novo sem a imposição do regime de separação obrigatória, ou para afastar cobranças de credores contra os herdeiros.",
      "Pode ser feito em cartório, com advogado, se os herdeiros forem capazes e estiverem de acordo."],
    sources: [["Código Civil, art. 1.523, I", P + "leis/2002/l10406compilada.htm"], ["Resolução CNJ 35/2007", "https://atos.cnj.jus.br/atos/detalhar/179"]], next: "Quer orientação para o seu caso?" },
  { id: "cessao-hereditaria", prio: 2, area: "cartorio", all: [["cessão de direitos", "cessao de direitos", "vender minha parte", "vender a parte da herança", "renúncia", "renuncia"]],
    q: "Posso vender ou renunciar à minha parte na herança?",
    a: ["Sim. A cessão de direitos hereditários deve ser feita por escritura pública. Os outros herdeiros têm preferência para comprar a sua parte nas mesmas condições.",
      "A renúncia também é feita por escritura pública ou por termo no processo, e não pode ser parcial nem sob condição. Quem renuncia é tratado como se nunca tivesse sido herdeiro.",
      "Renunciar “em favor” de alguém específico é, na prática, uma cessão, e gera ITCMD duas vezes."],
    sources: [["Código Civil, arts. 1.793 a 1.795 e 1.804 a 1.813", P + "leis/2002/l10406compilada.htm"]], next: "Quer avaliar a melhor forma?" },
  { id: "heranca-digital", area: "cartorio", all: [["herança digital", "heranca digital", "redes sociais de quem morreu", "conta do falecido", "senhas", "criptomoeda", "bitcoin"]],
    q: "O que acontece com contas digitais e criptomoedas de quem morreu?",
    a: ["Bens digitais com valor econômico (criptomoedas, saldos em plataformas, direitos autorais, domínios) entram no inventário como os demais bens.",
      "Contas pessoais (redes sociais, e-mail) seguem as regras de cada plataforma, que costumam permitir memorial ou exclusão a pedido da família. Ainda não há lei específica.",
      "O melhor caminho é o planejamento: listar ativos e acessos em testamento ou documento seguro."],
    sources: [["Código Civil, art. 1.784", P + "leis/2002/l10406compilada.htm"]], next: "Quer planejar seus bens digitais?" },
);

var ATLAS_EXTRA = Object.assign(typeof ATLAS_EXTRA === "undefined" ? {} : ATLAS_EXTRA, {
  "periodo-graca": "OPP-PREV-002", "auxilio-acidente": "OPP-PREV-007", "rural": "OPP-PREV-009", "conversao-especial": "OPP-PREV-008", "auxilio-reclusao": "OPP-PREV-003",
  "vida-toda": "OPP-PREV-005", "adicional-25": "OPP-PREV-002", "complementacao": "OPP-PREV-010", "tempo-militar": "OPP-PREV-001",
  "opme-protese": "OPP-SAU-002", "fertilizacao": "OPP-SAU-002", "portabilidade": "OPP-SAU-007", "uti-sus": "OPP-SAU-002", "odontologico": "OPP-SAU-010",
  "juros-abusivos": "OPP-BAN-005", "compra-nao-reconhecida": "OPP-BAN-006", "conta-invadida": "OPP-BAN-007", "tarifas-venda-casada": "OPP-BAN-005",
  "academia-curso": "OPP-CON-009", "turismo": "OPP-CON-010", "vazamento-dados": "OPP-CON-001",
  "direitos-servidor": "OPP-ADM-005", "improbidade": "OPP-ADM-007", "responsabilidade-estado": "OPP-ADM-010", "desapropriacao": "OPP-ADM-008", "lai": "OPP-ADM-010", "auto-infracao": "OPP-ADM-010",
  "compra-imovel": "OPP-IMO-004", "reurb": "OPP-IMO-009", "socioafetiva": "OPP-FAM-007", "regime-bens": "OPP-FAM-010", "apostila": "OPP-IMO-002",
  "alvara-valores": "OPP-SUC-006", "inventario-negativo": "OPP-SUC-010", "cessao-hereditaria": "OPP-SUC-009", "heranca-digital": "OPP-SUC-005",
});
